# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JokesApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JokesApp
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'SVProgressHUD'
  pod 'SDWebImage'

end
